'use client';

import { useState } from 'react';
import React from 'react';

import { motion } from 'framer-motion';
import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  CheckCircle,
  DollarSign,
  HelpCircle,
  Link as LinkIcon,
  Play,
  Share2,
  Target,
} from 'lucide-react';
import Link from 'next/link';

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { GoogleDriveVideoPlayer } from '@/components/ui/video-embed';

// Define types for our steps and metrics
interface StepType {
  title: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  content: React.ReactNode;
}

interface MetricType {
  metric: string;
  description: string;
  importance: string;
  optimization: string;
}

export default function ReferralSystemTutorial() {
  const [activeStep, setActiveStep] = useState(0);

  // Define tracking metrics first since they're used in the steps
  const trackingMetrics: MetricType[] = [
    {
      metric: 'Click Tracking',
      description: 'Monitor how many people click your referral links',
      importance: 'Measures reach and initial interest',
      optimization: 'Improve link placement and call-to-action',
    },
    {
      metric: 'Conversion Tracking',
      description: 'Track how many clicks become registered users',
      importance: 'Shows effectiveness of your targeting',
      optimization: 'Better audience targeting and content quality',
    },
    {
      metric: 'Activity Tracking',
      description: 'Monitor referred user engagement and bot usage',
      importance: 'Indicates long-term value of referrals',
      optimization: 'Provide better onboarding and support',
    },
    {
      metric: 'Revenue Attribution',
      description: 'Track earnings generated by each referral',
      importance: 'Calculates your commission earnings',
      optimization: 'Help referrals succeed to increase their usage',
    },
  ];

  // Define the steps after metrics since they reference them
  const steps: StepType[] = [
    {
      title: 'Generate Referral Link',
      description: 'Create your unique tracking link in the dashboard',
      icon: LinkIcon,
      content: (
        <div className="space-y-4">
          <h3 className="text-lg font-semibold">How to Generate Your Link</h3>
          <ol className="list-decimal pl-5 space-y-2 text-muted-foreground">
            <li>Go to your Ambassador Dashboard</li>
            <li>Navigate to the "Referral Links" section</li>
            <li>Click "Generate New Link" or use your default link</li>
            <li>
              Customize link parameters (optional):
              <ul className="list-disc pl-5 mt-1 space-y-1">
                <li>Campaign name for tracking</li>
                <li>Custom UTM parameters</li>
                <li>Specific bot or feature to highlight</li>
              </ul>
            </li>
            <li>Copy your unique referral link</li>
          </ol>
          <Alert className="mt-4">
            <AlertTitle>Pro Tip</AlertTitle>
            <AlertDescription>
              Create multiple links for different campaigns or platforms to
              track which ones perform best.
            </AlertDescription>
          </Alert>
        </div>
      ),
    },
    {
      title: 'Share & Promote',
      description: 'Distribute your link through various channels',
      icon: Share2,
      content: (
        <div className="space-y-4">
          <h3 className="text-lg font-semibold">
            Effective Sharing Strategies
          </h3>
          <div className="grid md:grid-cols-2 gap-4">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Best Platforms</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500" />
                  <span>Twitter/𝕏</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500" />
                  <span>Telegram Groups</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500" />
                  <span>Discord Communities</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500" />
                  <span>Crypto Forums</span>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Sharing Tips</CardTitle>
              </CardHeader>
              <CardContent className="space-y-2">
                <p className="text-sm">• Add value before sharing your link</p>
                <p className="text-sm">• Create tutorials or guides</p>
                <p className="text-sm">• Share your personal results</p>
                <p className="text-sm">• Engage with crypto communities</p>
              </CardContent>
            </Card>
          </div>
        </div>
      ),
    },
    {
      title: 'Track & Optimize',
      description: 'Monitor performance and improve conversion rates',
      icon: BarChart3,
      content: (
        <div className="space-y-4">
          <h3 className="text-lg font-semibold">Key Metrics to Monitor</h3>
          <div className="space-y-4">
            {trackingMetrics.map((metric, index) => (
              <div key={index} className="p-4 border rounded-lg">
                <h4 className="font-medium mb-1">{metric.metric}</h4>
                <p className="text-sm text-muted-foreground mb-2">
                  {metric.description}
                </p>
                <div className="text-xs text-muted-foreground">
                  <span className="font-medium">Why it matters:</span>{' '}
                  {metric.importance}
                </div>
              </div>
            ))}
          </div>
        </div>
      ),
    },
    {
      title: 'Earn Commissions',
      description: 'Receive payments from active referral usage',
      icon: DollarSign,
      content: (
        <div className="space-y-4">
          <h3 className="text-lg font-semibold">Commission Details</h3>
          <div className="grid md:grid-cols-2 gap-4">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Payout Structure</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <span>Direct Referrals</span>
                    <Badge>10%</Badge>
                  </div>
                  <div className="flex justify-between items-center">
                    <span>Indirect Referrals</span>
                    <Badge variant="outline">3%</Badge>
                  </div>
                  <div className="pt-2 mt-2 border-t">
                    <p className="text-sm text-muted-foreground">
                      Minimum Payout: $50
                    </p>
                    <p className="text-sm text-muted-foreground">
                      Payment Date: 1st of each month
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Maximize Earnings</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-start gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500 mt-1 flex-shrink-0" />
                  <span>Help your referrals succeed with onboarding</span>
                </div>
                <div className="flex items-start gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500 mt-1 flex-shrink-0" />
                  <span>
                    Create content showing how to use Valmira effectively
                  </span>
                </div>
                <div className="flex items-start gap-2">
                  <CheckCircle className="h-4 w-4 text-green-500 mt-1 flex-shrink-0" />
                  <span>
                    Focus on quality referrals who will be active long-term
                  </span>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      ),
    },
  ];

  const nextStep = () => {
    setActiveStep((prev) => (prev < steps.length - 1 ? prev + 1 : prev));
  };

  const prevStep = () => {
    setActiveStep((prev) => (prev > 0 ? prev - 1 : prev));
  };

  const goToStep = (index: number) => {
    setActiveStep(index);
  };

  // Tracking metrics moved to the top of the component

  return (
    <motion.div
      className="min-h-screen bg-background"
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          <Button variant="ghost" size="sm" asChild>
            <Link href="/tutorials">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Tutorials
            </Link>
          </Button>
        </div>

        <div className="max-w-4xl mx-auto space-y-8">
          {/* Title Section */}
          <div className="text-center space-y-4">
            <Badge variant="secondary" className="mb-4">
              Referral System Tutorial
            </Badge>
            <h1 className="text-4xl font-bold tracking-tight font-tt">
              Valmira Referral System Guide
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Master the referral system mechanics, tracking, and optimization
              strategies to maximize your ambassador earnings
            </p>
          </div>

          {/* Referral System Video Tutorial */}
          <Card className="border">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Play className="h-5 w-5" />
                Video Tutorial
              </CardTitle>
              <CardDescription>
                Watch this comprehensive guide to learn everything about the
                Valmira referral system
              </CardDescription>
            </CardHeader>
            <CardContent>
              <GoogleDriveVideoPlayer
                driveLink="https://drive.google.com/file/d/1T2bPrGeXuQkyvz_hAnteqXrxfwwQjBhk/view?usp=sharing"
                title="Valmira Referral System Complete Guide"
                description="Learn how to use the referral system to maximize your earnings"
                showInfo={true}
              />
            </CardContent>
          </Card>

          {/* Step Navigation */}
          <div className="space-y-8">
            <div className="relative">
              <div className="flex items-center justify-between">
                <div className="flex-1">
                  <div className="flex items-center">
                    {steps.map((step, index) => (
                      <React.Fragment key={index}>
                        <div className="flex flex-col items-center">
                          <button
                            onClick={() => goToStep(index)}
                            onKeyDown={(e) => {
                              if (e.key === 'Enter' || e.key === ' ') {
                                e.preventDefault();
                                goToStep(index);
                              }
                            }}
                            className={`relative flex h-12 w-12 items-center justify-center rounded-full transition-all duration-300 ${
                              index <= activeStep
                                ? 'bg-primary text-primary-foreground'
                                : 'bg-muted text-muted-foreground'
                            }`}
                            aria-label={`Go to step ${index + 1}: ${step.title}`}
                            aria-current={
                              index === activeStep ? 'step' : undefined
                            }
                          >
                            <step.icon className="h-5 w-5" />
                            {index < activeStep && (
                              <CheckCircle className="absolute -right-1 -top-1 h-5 w-5 rounded-full bg-background text-green-500" />
                            )}
                          </button>
                          <div
                            className={`mt-2 text-center text-xs font-medium ${
                              index === activeStep
                                ? 'text-foreground'
                                : 'text-muted-foreground'
                            }`}
                          >
                            {step.title.split(' ')[0]}
                          </div>
                        </div>
                        {index < steps.length - 1 && (
                          <div className="h-0.5 flex-1 bg-muted relative">
                            <div
                              className={`absolute left-0 top-0 h-full bg-primary transition-all duration-500 ${
                                index < activeStep ? 'w-full' : 'w-0'
                              }`}
                            />
                          </div>
                        )}
                      </React.Fragment>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Step Content */}
            <motion.div
              key={activeStep}
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.3 }}
              className="mt-8"
            >
              <Card>
                <CardHeader>
                  <div className="flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-primary">
                      {(() => {
                        const Icon = steps[activeStep].icon;
                        return <Icon className="h-5 w-5" />;
                      })()}
                    </div>
                    <div>
                      <CardTitle className="text-2xl">
                        {steps[activeStep].title}
                      </CardTitle>
                      <CardDescription>
                        {steps[activeStep].description}
                      </CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>{steps[activeStep].content}</CardContent>
              </Card>
            </motion.div>

            {/* Navigation Buttons */}
            <div className="flex justify-between pt-4">
              <Button
                variant="outline"
                onClick={prevStep}
                disabled={activeStep === 0}
                className={activeStep === 0 ? 'invisible' : ''}
              >
                <ArrowLeft className="mr-2 h-4 w-4" />
                Previous
              </Button>
              {activeStep < steps.length - 1 ? (
                <Button onClick={nextStep} className="ml-auto">
                  Next
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              ) : (
                <Button asChild>
                  <Link href="/dashboard/ambassador/referrals">
                    Go to Referral Dashboard
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              )}
            </div>
          </div>

          {/* How Referrals Work */}
          <Card className="border">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <HelpCircle className="h-5 w-5" />
                How the Referral System Works
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <h3 className="text-lg font-semibold mb-3">
                  Referral Mechanics
                </h3>
                <p className="text-muted-foreground mb-4">
                  The Valmira referral system uses unique tracking links to
                  attribute new users to ambassadors. When someone clicks your
                  referral link and signs up, they become permanently linked to
                  your account. You earn commissions on all their platform usage
                  for as long as they remain active.
                </p>
                <div className="bg-muted/50 p-4 rounded-lg">
                  <p className="font-medium mb-2">The Process:</p>
                  <ul className="space-y-2 text-sm">
                    <li>
                      <strong>1. Link Generation:</strong> System creates unique
                      tracking URL for your account
                    </li>
                    <li>
                      <strong>2. User Clicks:</strong> Potential user clicks
                      your referral link
                    </li>
                    <li>
                      <strong>3. Attribution:</strong> System records the
                      referral connection
                    </li>
                    <li>
                      <strong>4. Registration:</strong> User signs up and
                      becomes your referral
                    </li>
                    <li>
                      <strong>5. Commission Tracking:</strong> All their future
                      activity generates commissions for you
                    </li>
                  </ul>
                </div>
              </div>

              <div>
                <h3 className="text-lg font-semibold mb-3">Key Features</h3>
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="space-y-3">
                    <div className="flex items-start gap-3">
                      <CheckCircle className="h-5 w-5 text-green-500 mt-0.5" />
                      <div>
                        <p className="font-medium">Lifetime Attribution</p>
                        <p className="text-sm text-muted-foreground">
                          Referrals are permanently linked to your account
                        </p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <CheckCircle className="h-5 w-5 text-green-500 mt-0.5" />
                      <div>
                        <p className="font-medium">Real-time Tracking</p>
                        <p className="text-sm text-muted-foreground">
                          Daily processing of commissions and earnings via
                          automated cron jobs
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="space-y-3">
                    <div className="flex items-start gap-3">
                      <CheckCircle className="h-5 w-5 text-green-500 mt-0.5" />
                      <div>
                        <p className="font-medium">Multi-Channel Support</p>
                        <p className="text-sm text-muted-foreground">
                          Same link works across all platforms and devices
                        </p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <CheckCircle className="h-5 w-5 text-green-500 mt-0.5" />
                      <div>
                        <p className="font-medium">Fraud Protection</p>
                        <p className="text-sm text-muted-foreground">
                          Advanced systems prevent fake referrals and abuse
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Referral Flow */}
          <Card className="border">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Target className="h-5 w-5" />
                Complete Referral Flow
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                {steps.map((step: StepType, index: number) => (
                  <div
                    key={index}
                    className={`flex gap-4 p-4 rounded-lg border transition-colors ${
                      activeStep === index
                        ? 'bg-primary/5 border-primary'
                        : 'bg-muted/30'
                    }`}
                  >
                    <div className="flex-shrink-0">
                      <div
                        className={`w-10 h-10 rounded-full flex items-center justify-center ${
                          activeStep === index
                            ? 'bg-primary text-primary-foreground'
                            : 'bg-muted'
                        }`}
                      >
                        <step.icon className="h-5 w-5" />
                      </div>
                    </div>
                    <div className="flex-1">
                      <h3 className="font-semibold mb-2">{step.title}</h3>
                      <p className="text-muted-foreground mb-3">
                        {step.description}
                      </p>

                      {index === 0 && (
                        <div className="space-y-2 text-sm">
                          <p>
                            <strong>How to Generate Your Link:</strong>
                          </p>
                          <p>1. Go to Ambassador Dashboard Referral Links</p>
                          <p>
                            2. Click "Generate New Link" or use your default
                            link
                          </p>
                          <p>3. Customize link parameters (optional):</p>
                          <p className="ml-4">- Campaign name for tracking</p>
                          <p className="ml-4">
                            - Source identifier (twitter, youtube, etc.)
                          </p>
                          <p className="ml-4">- Custom landing page</p>
                          <p>4. Copy your unique referral URL</p>
                          <p>
                            <strong>Example:</strong>{' '}
                            https://valmira.xyz/ref/your-username?campaign=twitter
                          </p>
                        </div>
                      )}

                      {index === 1 && (
                        <div className="space-y-2 text-sm">
                          <p>
                            <strong>Effective Sharing Strategies:</strong>
                          </p>
                          <p>
                            1. <strong>Social Media:</strong> Twitter threads,
                            LinkedIn posts, Discord messages
                          </p>
                          <p>
                            2. <strong>Content Marketing:</strong> Blog posts,
                            YouTube videos, newsletters
                          </p>
                          <p>
                            3. <strong>Direct Outreach:</strong> Personal
                            messages to potential users
                          </p>
                          <p>
                            4. <strong>Community Engagement:</strong> Answer
                            questions and provide value first
                          </p>
                          <p>
                            5. <strong>Educational Content:</strong> Tutorials
                            that naturally include your link
                          </p>
                          <p>
                            <strong>Best Practice:</strong> Always provide value
                            before promoting
                          </p>
                        </div>
                      )}

                      {index === 2 && (
                        <div className="space-y-2 text-sm">
                          <p>
                            <strong>Key Metrics to Monitor:</strong>
                          </p>
                          <p>
                            1. <strong>Click-Through Rate:</strong> Clicks ÷
                            Impressions
                          </p>
                          <p>
                            2. <strong>Conversion Rate:</strong> Sign-ups ÷
                            Clicks
                          </p>
                          <p>
                            3. <strong>Activation Rate:</strong> Active users ÷
                            Sign-ups
                          </p>
                          <p>
                            4. <strong>Revenue per User:</strong> Total
                            commissions ÷ Active referrals
                          </p>
                          <p>
                            <strong>Optimization Tips:</strong>
                          </p>
                          <p>- Test different content types and messaging</p>
                          <p>
                            - Focus on channels with highest conversion rates
                          </p>
                          <p>- Provide better onboarding for new referrals</p>
                        </div>
                      )}

                      {index === 3 && (
                        <div className="space-y-2 text-sm">
                          <p>
                            <strong>Commission Structure:</strong>
                          </p>
                          <p>
                            1. <strong>Real-time Tracking:</strong> See earnings
                            update instantly
                          </p>
                          <p>
                            2. <strong>Monthly Payments:</strong> Commissions
                            paid on 1st of each month
                          </p>
                          <p>
                            3. <strong>Minimum Threshold:</strong> $50 minimum
                            for payout
                          </p>
                          <p>
                            4. <strong>Payment Methods:</strong> USDC, BNB, or
                            ETH to your wallet
                          </p>
                          <p>
                            <strong>Commission Rates (All Users):</strong>
                          </p>
                          <p>- Level 1 (Direct Referrals): 10%</p>
                          <p>- Level 2 (Indirect Referrals): 3%</p>
                          <p>- No tiers or minimums required</p>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Tracking & Analytics */}
          <Card className="border">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="h-5 w-5" />
                Tracking & Analytics Deep Dive
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Tabs defaultValue="metrics" className="w-full">
                <TabsList className="grid w-full grid-cols-3">
                  <TabsTrigger value="metrics">Key Metrics</TabsTrigger>
                  <TabsTrigger value="dashboard">
                    Dashboard Features
                  </TabsTrigger>
                  <TabsTrigger value="optimization">Optimization</TabsTrigger>
                </TabsList>

                <TabsContent value="metrics" className="space-y-4">
                  <div className="space-y-4">
                    {trackingMetrics.map((metric, index) => (
                      <Card key={index} className="border">
                        <CardHeader>
                          <CardTitle className="text-lg">
                            {metric.metric}
                          </CardTitle>
                          <CardDescription>
                            {metric.description}
                          </CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-3">
                          <div>
                            <p className="font-medium text-blue-600">
                              Why It Matters:
                            </p>
                            <p className="text-sm">{metric.importance}</p>
                          </div>
                          <div>
                            <p className="font-medium text-green-600">
                              How to Optimize:
                            </p>
                            <p className="text-sm">{metric.optimization}</p>
                          </div>
                        </CardContent>
                      </Card>
                    ))}
                  </div>
                </TabsContent>

                <TabsContent value="dashboard" className="space-y-4">
                  <div>
                    <h4 className="font-semibold mb-3">
                      Ambassador Dashboard Features
                    </h4>
                    <div className="grid md:grid-cols-2 gap-4 text-sm">
                      <div>
                        <p className="font-medium mb-2">Real-time Analytics:</p>
                        <ul className="space-y-1 ml-4">
                          <li>- Live click and conversion tracking</li>
                          <li>- Revenue attribution by referral</li>
                          <li>- Performance trends and charts</li>
                          <li>- Geographic distribution of clicks</li>
                        </ul>
                      </div>
                      <div>
                        <p className="font-medium mb-2">Management Tools:</p>
                        <ul className="space-y-1 ml-4">
                          <li>- Multiple referral link creation</li>
                          <li>- Campaign tagging and organization</li>
                          <li>- Referral contact management</li>
                          <li>- Commission history and projections</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div>
                    <h4 className="font-semibold mb-3">Advanced Features</h4>
                    <ul className="space-y-2 text-sm">
                      <li>
                        <strong>A/B Testing:</strong> Test different landing
                        pages and track performance
                      </li>
                      <li>
                        <strong>Cohort Analysis:</strong> Compare referral
                        groups by time period or source
                      </li>
                      <li>
                        <strong>Lifetime Value Tracking:</strong> Monitor
                        long-term value of each referral
                      </li>
                      <li>
                        <strong>Automated Alerts:</strong> Get notified of
                        important events and milestones
                      </li>
                    </ul>
                  </div>
                </TabsContent>

                <TabsContent value="optimization" className="space-y-4">
                  <Alert>
                    <Target className="h-4 w-4" />
                    <AlertTitle>Optimization Strategy</AlertTitle>
                    <AlertDescription>
                      Focus on quality over quantity. Better to have fewer
                      high-value referrals than many inactive ones.
                    </AlertDescription>
                  </Alert>

                  <div className="space-y-4">
                    <div>
                      <h4 className="font-semibold mb-3">
                        Conversion Rate Optimization
                      </h4>
                      <ul className="space-y-2 text-sm">
                        <li>
                          <strong>Target the Right Audience:</strong> Focus on
                          people who actually need token marketing tools
                        </li>
                        <li>
                          <strong>Provide Value First:</strong> Share helpful
                          content before promoting Valmira
                        </li>
                        <li>
                          <strong>Use Social Proof:</strong> Share your own
                          results and success stories
                        </li>
                        <li>
                          <strong>Clear Call-to-Action:</strong> Make it obvious
                          what you want people to do
                        </li>
                        <li>
                          <strong>Address Objections:</strong> Anticipate and
                          answer common concerns
                        </li>
                      </ul>
                    </div>
                    <div>
                      <h4 className="font-semibold mb-3">
                        Retention & Activation
                      </h4>
                      <ul className="space-y-2 text-sm">
                        <li>
                          <strong>Onboarding Support:</strong> Help new
                          referrals get started successfully
                        </li>
                        <li>
                          <strong>Educational Content:</strong> Create tutorials
                          specific to your referrals
                        </li>
                        <li>
                          <strong>Community Building:</strong> Create groups for
                          your referrals to connect
                        </li>
                        <li>
                          <strong>Regular Check-ins:</strong> Follow up to
                          ensure they're getting value
                        </li>
                        <li>
                          <strong>Success Sharing:</strong> Celebrate and share
                          referral wins
                        </li>
                      </ul>
                    </div>
                  </div>
                </TabsContent>
              </Tabs>
            </CardContent>
          </Card>

          {/* Advanced Strategies */}
          <Card className="border">
            <CardHeader>
              <CardTitle>Advanced Referral Strategies</CardTitle>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="w-full">
                <AccordionItem value="content-marketing">
                  <AccordionTrigger>
                    Content Marketing Strategies
                  </AccordionTrigger>
                  <AccordionContent className="space-y-4">
                    <div>
                      <h4 className="font-semibold mb-2">
                        Educational Content Approach
                      </h4>
                      <ul className="space-y-2 text-sm">
                        <li>
                          <strong>Tutorial Series:</strong> Create step-by-step
                          guides for token marketing
                        </li>
                        <li>
                          <strong>Case Studies:</strong> Document real projects
                          and their results
                        </li>
                        <li>
                          <strong>Comparison Content:</strong> Compare Valmira
                          to alternatives
                        </li>
                        <li>
                          <strong>Industry Insights:</strong> Share trends and
                          predictions in token marketing
                        </li>
                      </ul>
                    </div>
                    <div>
                      <h4 className="font-semibold mb-2">
                        Content Distribution
                      </h4>
                      <ul className="space-y-2 text-sm">
                        <li>
                          <strong>Multi-Platform Strategy:</strong> Repurpose
                          content across different channels
                        </li>
                        <li>
                          <strong>SEO Optimization:</strong> Target keywords
                          related to token marketing
                        </li>
                        <li>
                          <strong>Community Engagement:</strong> Share in
                          relevant Discord/Telegram groups
                        </li>
                        <li>
                          <strong>Influencer Collaboration:</strong> Partner
                          with other crypto content creators
                        </li>
                      </ul>
                    </div>
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem value="relationship-building">
                  <AccordionTrigger>
                    Relationship Building & Support
                  </AccordionTrigger>
                  <AccordionContent className="space-y-4">
                    <div>
                      <h4 className="font-semibold mb-2">Building Trust</h4>
                      <ul className="space-y-2 text-sm">
                        <li>
                          <strong>Transparency:</strong> Be open about your
                          ambassador status and earnings
                        </li>
                        <li>
                          <strong>Authentic Recommendations:</strong> Only
                          promote what you genuinely use and believe in
                        </li>
                        <li>
                          <strong>Responsive Support:</strong> Quickly help
                          referrals with questions and issues
                        </li>
                        <li>
                          <strong>Long-term Thinking:</strong> Focus on building
                          lasting relationships, not quick conversions
                        </li>
                      </ul>
                    </div>
                    <div>
                      <h4 className="font-semibold mb-2">
                        Ongoing Support Strategy
                      </h4>
                      <ul className="space-y-2 text-sm">
                        <li>
                          <strong>Welcome Sequence:</strong> Structured
                          onboarding for new referrals
                        </li>
                        <li>
                          <strong>Regular Check-ins:</strong> Monthly calls or
                          messages to ensure success
                        </li>
                        <li>
                          <strong>Exclusive Content:</strong> Special tutorials
                          and tips for your referrals
                        </li>
                        <li>
                          <strong>Success Celebration:</strong> Highlight and
                          share referral achievements
                        </li>
                      </ul>
                    </div>
                  </AccordionContent>
                </AccordionItem>

                <AccordionItem value="scaling-strategies">
                  <AccordionTrigger>Scaling & Automation</AccordionTrigger>
                  <AccordionContent className="space-y-4">
                    <div>
                      <h4 className="font-semibold mb-2">
                        Scaling Your Efforts
                      </h4>
                      <ul className="space-y-2 text-sm">
                        <li>
                          <strong>Content Automation:</strong> Use scheduling
                          tools for consistent posting
                        </li>
                        <li>
                          <strong>Email Sequences:</strong> Automated follow-up
                          sequences for new referrals
                        </li>
                        <li>
                          <strong>Community Building:</strong> Create
                          self-sustaining communities around your content
                        </li>
                        <li>
                          <strong>Team Building:</strong> Consider hiring help
                          for content creation and management
                        </li>
                      </ul>
                    </div>
                    <div>
                      <h4 className="font-semibold mb-2">
                        Performance Optimization
                      </h4>
                      <ul className="space-y-2 text-sm">
                        <li>
                          <strong>Data-Driven Decisions:</strong> Use analytics
                          to guide strategy changes
                        </li>
                        <li>
                          <strong>Continuous Testing:</strong> Always be testing
                          new approaches and content
                        </li>
                        <li>
                          <strong>Feedback Loops:</strong> Regularly survey
                          referrals for improvement ideas
                        </li>
                        <li>
                          <strong>Competitive Analysis:</strong> Study
                          successful ambassadors and adapt their strategies
                        </li>
                      </ul>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            </CardContent>
          </Card>

          {/* Quick Start CTA */}
          <Card className="border bg-primary/5">
            <CardContent className="pt-6">
              <div className="text-center space-y-4">
                <h3 className="text-xl font-semibold">
                  Ready to Master the Referral System?
                </h3>
                <p className="text-muted-foreground">
                  Start implementing these strategies to maximize your referral
                  success and earnings
                </p>
                <div className="flex gap-4 justify-center">
                  <Button asChild>
                    <Link href="/ambassador">Access Dashboard</Link>
                  </Button>
                  <Button variant="outline" asChild>
                    <Link href="/tutorials/ambassador/payment-settings">
                      Setup Payments
                    </Link>
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </motion.div>
  );
}
