'use client';

import { TrendingUp, ChartColumnIncreasing, Share, ScreenShare } from 'lucide-react';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { mockAmbassadorEarningsBreakdownData } from '@/lib/mock-data';
import { DataChart } from '@/components/ui/data-chart';

export function AmbassadorOverview() {
  return (
    <div className="space-y-4 md:space-y-6">
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {/* Lifetime Earning */}
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium">Lifetime Earning</CardTitle>
              <TrendingUp className="h-4 w-4 text-muted-foreground" />
            </div>
            <div className="mt-2">
              <div className="text-2xl font-bold">$2,802.00</div>
              <p className="text-xs text-muted-foreground">Total earnings</p>
            </div>
          </CardContent>
        </Card>

        {/* Today's Earnings */}
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium">Today's Earnings</CardTitle>
              <ChartColumnIncreasing className="h-4 w-4 text-muted-foreground" />
            </div>
            <div className="mt-2">
              <div className="text-2xl font-bold">$45.55</div>
              <p className="text-xs text-green-600">+12% from yesterday</p>
            </div>
          </CardContent>
        </Card>

        {/* Direct Referral */}
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium">Direct Referral</CardTitle>
              <Share className="h-4 w-4 text-muted-foreground" />
            </div>
            <div className="mt-2">
              <div className="text-2xl font-bold">3</div>
              <p className="text-xs text-muted-foreground">Level 1 projects you've referred</p>
            </div>
          </CardContent>
        </Card>

        {/* Indirect Referral */}
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium">Indirect Referral</CardTitle>
              <ScreenShare className="h-4 w-4 text-muted-foreground" />
            </div>
            <div className="mt-2">
              <div className="text-2xl font-bold">3</div>
              <p className="text-xs text-muted-foreground">Level 2 projects from your network</p>
            </div>
          </CardContent>
        </Card>
      </div>
   
      <DataChart
        title="Earning over time"
        description="Your daily earning from the ambassador programs"
        data={mockAmbassadorEarningsBreakdownData}
        dataKey="numberOfBots"
        color="hsl(var(--chart-1))"
      />

      <div className="grid gap-4 md:grid-cols-2">
        {/* Commission structure */}
        <Card>
          <CardHeader>
            <CardTitle>Commission structure</CardTitle>
            <p className="text-sm text-muted-foreground">How you earn from referred projects</p>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-4">
              <div className="space-y-2 border rounded-md p-4">
                <h4 className="font-medium">Level 1 : Direct Referrals</h4>
                <p className="text-sm text-muted-foreground">
                  You earn 10% of all fees generated by projects that sign up using your unique link.
                </p>
              </div>
              <div className="space-y-2 border rounded-md p-4">
                <h4 className="font-medium">Level 2 : Indirect Referrals</h4>
                <p className="text-sm text-muted-foreground">
                  You earn 3% of all fees generated by projects that your direct referrals bring to Valmira.
                </p>
              </div>
              <div className="space-y-2 border rounded-md p-4">
                <h4 className="font-medium">Lifetime Payout</h4>
                <p className="text-sm text-muted-foreground">
                  As long as a referred project continues using Valmira, you keep earning daily from their fees.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Quick Stats */}
        <Card>
          <CardHeader>
            <CardTitle>Quick Stats</CardTitle>
            <p className="text-sm text-muted-foreground">Your ambassador performance at a glance</p>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="flex justify-between py-2">
                <span className="text-foreground">Weekly Earnings</span>
                <span className="font-medium">$1234</span>
              </div>
              <div className="flex justify-between py-2">
                <span className="text-foreground">Monthly Earnings</span>
                <span className="font-medium">$1234</span>
              </div>
              <div className="flex justify-between py-2">
                <span className="text-foreground">Average Daily Earning</span>
                <span className="font-medium">$1234</span>
              </div>
              <div className="flex justify-between py-2">
                <span className="text-foreground">Most Profitable Referral</span>
                <span className="font-medium">PEPE ($123)</span>
              </div>
              <div className="flex justify-between py-2">
                <span className="text-foreground">Ambassador Rank</span>
                <span className="font-medium">Silver</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
} 