// Mock data for charts
export const mockChartData = [
  { name: 'Jan', value: 4000, date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString() },
  { name: 'Feb', value: 3000, date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString() },
  { name: 'Mar', value: 5000, date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString() },
  { name: 'Apr', value: 2780, date: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString() },
  { name: 'May', value: 1890, date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString() },
  { name: 'Jun', value: 2390, date: new Date(new Date().setDate(new Date().getDate() - 6)).toISOString() },
  { name: 'Jul', value: 3490, date: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString() },
  { name: 'Aug', value: 2000, date: new Date(new Date().setDate(new Date().getDate() - 8)).toISOString() },
  { name: 'Sep', value: 2780, date: new Date(new Date().setDate(new Date().getDate() - 9)).toISOString() },
  { name: 'Oct', value: 1890, date: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString() },
  { name: 'Nov', value: 2390, date: new Date(new Date().setDate(new Date().getDate() - 11)).toISOString() },
  { name: 'Dec', value: 3490, date: new Date(new Date().setDate(new Date().getDate() - 12)).toISOString() },
];

// Mock data for portfolio performance
export const mockPortfolioData = [
  { name: 'Jan', profit: 4000, volume: 240000, trades: 240, date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString() },
  { name: 'Feb', profit: 3000, volume: 198000, trades: 210, date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString() },
  { name: 'Mar', profit: 5000, volume: 280000, trades: 250, date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString() },
  { name: 'Apr', profit: 2780, volume: 308000, trades: 290, date: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString() },
  { name: 'May', profit: 1890, volume: 248000, trades: 230, date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString() },
  { name: 'Jun', profit: 2390, volume: 380000, trades: 310, date: new Date(new Date().setDate(new Date().getDate() - 6)).toISOString() },
  { name: 'Jul', profit: 3490, volume: 430000, trades: 340, date: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString() },
  { name: 'Aug', profit: 2000, volume: 290000, trades: 270, date: new Date(new Date().setDate(new Date().getDate() - 8)).toISOString() },
  { name: 'Sep', profit: 2780, volume: 320000, trades: 300, date: new Date(new Date().setDate(new Date().getDate() - 9)).toISOString() },
  { name: 'Oct', profit: 1890, volume: 260000, trades: 240, date: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString() },
  { name: 'Nov', profit: 2390, volume: 350000, trades: 290, date: new Date(new Date().setDate(new Date().getDate() - 11)).toISOString() },
  { name: 'Dec', profit: 3490, volume: 410000, trades: 330, date: new Date(new Date().setDate(new Date().getDate() - 12)).toISOString() },
];

// Mock data for ambassador earnings
export const mockAmbassadorEarningsBreakdownData = [
  {
    projectName: 'PEPE',
    dailyBotFee: '$1232',
    numberOfBots: 3,
    totalFee: '$12.22',
    percentage: '10%',
    earnings: '$123.22',
    date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    projectName: 'SHIB',
    dailyBotFee: '$1232',
    numberOfBots: 2,
    totalFee: '$12.22',
    percentage: '10%',
    earnings: '$123.22',
    date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    projectName: 'DOGE',
    dailyBotFee: '$1232',
    numberOfBots: 4,
    totalFee: '$12.22',
    percentage: '10%',
    earnings: '$123.22',
    date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
  {
    projectName: 'MetaToken',
    dailyBotFee: '$1232',
    numberOfBots: 1,
    totalFee: '$12.22',
    percentage: '10%',
    earnings: '$123.22',
    date: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
  },
  {
    projectName: 'GameFi',
    dailyBotFee: '$1232',
    numberOfBots: 2,
    totalFee: '$12.22',
    percentage: '10%',
    earnings: '$123.22',
    date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
  },
  {
    projectName: 'PEPE',
    dailyBotFee: '$1450',
    numberOfBots: 5,
    totalFee: '$14.50',
    percentage: '10%',
    earnings: '$145.00',
    date: new Date(new Date().setDate(new Date().getDate() - 6)).toISOString(),
  },
  {
    projectName: 'SHIB',
    dailyBotFee: '$980',
    numberOfBots: 3,
    totalFee: '$9.80',
    percentage: '10%',
    earnings: '$98.00',
    date: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
  },
  {
    projectName: 'DOGE',
    dailyBotFee: '$1567',
    numberOfBots: 6,
    totalFee: '$15.67',
    percentage: '10%',
    earnings: '$156.70',
    date: new Date(new Date().setDate(new Date().getDate() - 8)).toISOString(),
  },
  {
    projectName: 'MetaToken',
    dailyBotFee: '$890',
    numberOfBots: 2,
    totalFee: '$8.90',
    percentage: '10%',
    earnings: '$89.00',
    date: new Date(new Date().setDate(new Date().getDate() - 9)).toISOString(),
  },
  {
    projectName: 'GameFi',
    dailyBotFee: '$2100',
    numberOfBots: 4,
    totalFee: '$21.00',
    percentage: '10%',
    earnings: '$210.00',
    date: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
  },
  {
    projectName: 'PEPE',
    dailyBotFee: '$1890',
    numberOfBots: 7,
    totalFee: '$18.90',
    percentage: '10%',
    earnings: '$189.00',
    date: new Date(new Date().setDate(new Date().getDate() - 11)).toISOString(),
  },
  {
    projectName: 'SHIB',
    dailyBotFee: '$1345',
    numberOfBots: 4,
    totalFee: '$13.45',
    percentage: '10%',
    earnings: '$134.50',
    date: new Date(new Date().setDate(new Date().getDate() - 12)).toISOString(),
  },
  {
    projectName: 'DOGE',
    dailyBotFee: '$1678',
    numberOfBots: 5,
    totalFee: '$16.78',
    percentage: '10%',
    earnings: '$167.80',
    date: new Date(new Date().setDate(new Date().getDate() - 13)).toISOString(),
  },
  {
    projectName: 'MetaToken',
    dailyBotFee: '$2345',
    numberOfBots: 8,
    totalFee: '$23.45',
    percentage: '10%',
    earnings: '$234.50',
    date: new Date(new Date().setDate(new Date().getDate() - 14)).toISOString(),
  },
  {
    projectName: 'GameFi',
    dailyBotFee: '$1234',
    numberOfBots: 3,
    totalFee: '$12.34',
    percentage: '10%',
    earnings: '$123.40',
    date: new Date(new Date().setDate(new Date().getDate() - 15)).toISOString(),
  },
  {
    projectName: 'PEPE',
    dailyBotFee: '$1789',
    numberOfBots: 6,
    totalFee: '$17.89',
    percentage: '10%',
    earnings: '$178.90',
    date: new Date(new Date().setDate(new Date().getDate() - 16)).toISOString(),
  },
  {
    projectName: 'SHIB',
    dailyBotFee: '$2100',
    numberOfBots: 7,
    totalFee: '$21.00',
    percentage: '10%',
    earnings: '$210.00',
    date: new Date(new Date().setDate(new Date().getDate() - 17)).toISOString(),
  },
  {
    projectName: 'DOGE',
    dailyBotFee: '$1456',
    numberOfBots: 4,
    totalFee: '$14.56',
    percentage: '10%',
    earnings: '$145.60',
    date: new Date(new Date().setDate(new Date().getDate() - 18)).toISOString(),
  },
  {
    projectName: 'MetaToken',
    dailyBotFee: '$1890',
    numberOfBots: 5,
    totalFee: '$18.90',
    percentage: '10%',
    earnings: '$189.00',
    date: new Date(new Date().setDate(new Date().getDate() - 19)).toISOString(),
  },
  {
    projectName: 'GameFi',
    dailyBotFee: '$2345',
    numberOfBots: 8,
    totalFee: '$23.45',
    percentage: '10%',
    earnings: '$234.50',
    date: new Date(new Date().setDate(new Date().getDate() - 20)).toISOString(),
  }
]; 

export const mockAmbassadorPaymentSettingsData = [
  {
    date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    amount: '$55.22',
    to: 'USDT',
    status: 'Completed',
    txHash: '102113_139021'
  },
  {
    date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    amount: '$123.22',
    to: 'USDC',
    status: 'failed',
    txHash: '102013_139021'
  },
  {
    date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    amount: '$123.22',
    to: 'USDC',
    status: 'Completed',
    txHash: '102013_139021'
  },
  {
    date: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
    amount: '$123.22',
    to: 'USDC',
    status: 'Completed',
    txHash: '102013_139021'
  },
  {
    date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    amount: '$123.22',
    to: 'USDC',
    status: 'Completed',
    txHash: '102013_139021'
  },
  {
    date: new Date(new Date().setDate(new Date().getDate() - 6)).toISOString(),
    amount: '$123.22',
    to: 'USDC',
    status: 'Completed',
    txHash: '102013_139021'
  }
];

export const mockPortfolioProjects = [
  {
    id: '1',
    name: 'TokenX',
    contractAddress: '0x1234...5678',
    network: 'Ethereum',
    status: 'Active',
    profit: 12500,
    profitChange: 15.2,
    volume: 450000,
    volumeChange: 8.7,
    trades: 850,
    tradesChange: 5.3,
    profitTrend: [100, 120, 110, 130, 150, 140, 160],
    volumeTrend: [1000, 1200, 1100, 1300, 1500, 1400, 1600],
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
  },
  {
    id: '2',
    name: 'CryptoY',
    contractAddress: '0x9876...5432',
    network: 'BSC',
    status: 'Active',
    profit: 8200,
    profitChange: -3.5,
    volume: 320000,
    volumeChange: 12.1,
    trades: 620,
    tradesChange: 9.8,
    profitTrend: [80, 85, 90, 88, 92, 95, 98],
    volumeTrend: [900, 950, 980, 970, 990, 1000, 987],
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
  },
  {
    id: '3',
    name: 'DeFiZ',
    contractAddress: '0xabcd...ef12',
    network: 'Polygon',
    status: 'Active',
    profit: 3980,
    profitChange: 22.7,
    volume: 180000,
    volumeChange: 15.3,
    trades: 372,
    tradesChange: -2.1,
    profitTrend: [50, 55, 60, 58, 56, 54, 55],
    volumeTrend: [500, 520, 550, 540, 530, 545, 543],
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
  },
  {
    id: '4',
    name: 'MetaToken',
    contractAddress: '0xfedc...ba98',
    network: 'Arbitrum',
    status: 'Paused',
    profit: 0,
    profitChange: 0,
    volume: 0,
    volumeChange: 0,
    trades: 0,
    tradesChange: 0,
    profitTrend: [40, 45, 50, 48, 46, 44, 0],
    volumeTrend: [400, 420, 450, 440, 430, 445, 0],
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 4)).toISOString(),
  },
  {
    id: '5',
    name: 'GameFi',
    contractAddress: '0x7654...3210',
    network: 'Optimism',
    status: 'Active',
    profit: 0,
    profitChange: 0,
    volume: 300000,
    volumeChange: 18.9,
    trades: 0,
    tradesChange: 0,
    profitTrend: [40, 45, 50, 48, 46, 44, 0],
    volumeTrend: [300, 320, 350, 340, 330, 345, 343],
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
  },
  {
    id: '6',
    name: 'GameFiX',
    contractAddress: '0x7654...3210',
    network: 'Optimism',
    status: 'Active',
    profit: 0,
    profitChange: 0,
    volume: 300000,
    volumeChange: 18.9,
    trades: 0,
    tradesChange: 0,
    profitTrend: [40, 45, 50, 48, 46, 44, 0],
    volumeTrend: [300, 320, 350, 340, 330, 345, 343],
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 6)).toISOString(),
  },
  {
    id: '7',
    name: 'Optimism',
    contractAddress: '0x7654...3210',
    network: 'Optimism',
    status: 'Active',
    profit: 0,
    profitChange: 0,
    volume: 300000,
    volumeChange: 18.9,
    trades: 0,
    tradesChange: 0,
    profitTrend: [40, 45, 50, 48, 46, 44, 0],
    volumeTrend: [300, 320, 350, 340, 330, 345, 343],
    lastUpdated: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
  },
];